### PR TITLE
Switch toolkit methods to php functions

### PR DESCRIPTION
**Pull request by afbora**
I'll also take care linux commands in separate PR.

### CODE REVIEW

**Review by lukasbestle — APPROVED** [review]

**Review by bastianallgeier — CHANGES_REQUESTED** [review]
Sorry to cause confusion. But we can safely use toolkit methods in commands that require a Kirby installation. There's no need to move everything to simple PHP. We just can't use it in commands that might come from a place where Kirby isn't installed yet

**Comment by afbora** [comment]
I understand. So we can just close the PR? @bastianallgeier

**Comment by lukasbestle** [comment]
@bastianallgeier But wouldn't it still be safer to be independent from the installed Kirby version?

**Comment by bastianallgeier** [comment]
@lukasbestle In some cases probably yes. But I'm not sure what would be the best way to solve this. Is there a good way to also include Kirby as a composer dependency and use that one whenever possible and only use the installed version when it is really needed to do so?

**Comment by lukasbestle** [comment]
Not really. I think the classes will compete with each other as each class can only be loaded once.

**Pull request closed without merging**
