### PR TITLE
`make:plugin`: also create JS file

### PR DESCRIPTION
**Pull request by distantnative**

### CODE REVIEW

**Review by lukasbestle — COMMENTED** [review]
Not sure TBH, could be too opinionated. Plugins without Panel extensions wouldn't need the file at all and plugins with a build setup would rather expect a JS file in `src/index.js`. The `index.php` is the only file that is always useful.

**Comment by distantnative** [comment]
Ok true the `src/index.js` argument convinces me. I thought it could also be the other way around: only JS needed, no PHP.

**Comment by lukasbestle** [comment]
With the update check, the anonymous plugins without PHP file have become less relevant (only for private plugins).

**Comment by distantnative** [comment]
@lukasbestle yes, but that's also what this command will be most used for

**Pull request closed without merging**
